# Workflow name (GitHub Actions tab এ এই নাম দেখাবে)
name: First Workflow

# Trigger event
# মানে: যখন main branch এ code push হবে, তখন workflow run হবে
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch

jobs:
  # একটি job তৈরি করা হয়েছে যার নাম first-workflow
  first-workflow:
    # কোন machine এ run হবে (runner)
    runs-on: ubuntu-latest

    steps:
      # প্রথম step: simple message print করা
      - name: First Step
        run: echo "Hello, GitHub Actions 🚀"
