# Workflow name
name: Matrix Workflow

# Manual trigger
on:
  workflow_dispatch:

jobs:
  test:
    # Runner machine
    runs-on: ubuntu-latest

    # Matrix strategy = same job multiple times run হবে
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      # Setup Node.js version from matrix
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      # Check current version
      - name: Show Node.js Version
        run: node -v
